<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <RootNamespace>FoodDelivery</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="8.2.1" />
    <PackageReference Include="Volo.Abp.Identity.HttpApi" Version="8.2.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FoodDelivery.Application.Contracts\FoodDelivery.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
