<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <RootNamespace>FoodDelivery</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.TestBase" Version="8.2.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.6.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.4" />
    <PackageReference Include="Shouldly" Version="4.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FoodDelivery.Application\FoodDelivery.Application.csproj" />
    <ProjectReference Include="..\..\src\FoodDelivery.EntityFrameworkCore\FoodDelivery.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
